INSERT INTO public.accounts VALUES (16, 'capital expenses', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (32, 'accounting', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (21, 'feed', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (40, 'printing and reproduction', 'aka communication, copying', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (58, 'CSA supplies', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (59, 'taxes, employment', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (61, 'supplies, office', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (63, 'chemicals', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (31, 'gifts', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (70, 'training', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (88, 'cc', 'This is a credit card, which one needs in order to rent an auto. This is used for online payments.', 'suppliers', 'Y 2017-07-10', 'in progress', NULL, 'mudiacom_soiltoil', '72', 'budget stock deducts 13 monthly from cc', NULL, NULL);
INSERT INTO public.accounts VALUES (130, 'paypal', 'This is an internet bank and epay services. This is the PayPal balance. This is a type of paypal acount known as the personal account.', 'suppliers', 'Y 2017-08-21', 'in progress', NULL, 'mudiacom_soiltoil', '80', 'budget stock', NULL, NULL);
INSERT INTO public.accounts VALUES (110, 'patagonia', 'I work at the store on Newbury St. in Boston. See my goals on workday. See <kbd>hackagonia</kbd> project.', 'projects', 'Y 2017-08-21', 'in progress', NULL, 'mudiacom_soiltoil', '50', 'moneymaker earn 500 biweekly', NULL, NULL);
INSERT INTO public.accounts VALUES (24, 'health', 'Doctor and dentist and eye doctor.', 'designs', 'Y 2017-07-10', 'in progress', NULL, 'mudiacom_soiltoil', '1232', 'budget quarterly', NULL, NULL);
INSERT INTO public.accounts VALUES (75, 'transport', 'Includes car and truck, train, plane, bike. Also insurance for vehicle, equipment, and other need relationships. Zipcar, uber, and autonomous vehicles.', 'processes', 'Y 2017-07-10', 'in progress', NULL, 'mudiacom_soiltoil', '84', 'budget pay 90 per week', NULL, NULL);
INSERT INTO public.accounts VALUES (133, 'house-supplies', 'Chip in and pay portion of supplies for the house.', 'lands', 'Y 2017-07-10', 'in progress', '', 'mudiacom_soiltoil', '154', 'budget pay 25 monthly cash ', NULL, NULL);
INSERT INTO public.accounts VALUES (116, 'wardrobe', 'The clothes to wear, a second skin, costumes.', 'suppliers', 'Y 2017-01-01', 'in progress', NULL, 'mudiacom_soiltoil', '81', 'budget pay 60 monthly', NULL, NULL);
INSERT INTO public.accounts VALUES (126, 'attorney', 'A lawyer for the legal matters such as incorporating. This is the organizational entity. At its core, Radiant Bunny is an idea and a common trust.', 'designs', 'Y 2017-01-01', 'in progress', NULL, 'mudiacom_soiltoil', '47', 'radiant bunny llp', NULL, NULL);
INSERT INTO public.accounts VALUES (132, 'music', 'stream music', 'processes', 'Y 2017-01-01', 'offline', NULL, 'mudiacom_soiltoil', '54', 'budget deducts 5 monthly from cc', NULL, NULL);
INSERT INTO public.accounts VALUES (129, 'entertainment', 'Go to the movies and enjoy the arts.', 'designs', 'Y 2017-01-01', 'in progress', NULL, 'mudiacom_soiltoil', '51', 'budget quarterly', NULL, NULL);
INSERT INTO public.accounts VALUES (127, 'access', 'This is to pay the Internet Service Provider, the service to connect to the Internet.', 'tools', 'Y 2017-01-01', 'offline', NULL, 'mudiacom_soiltoil', '78', NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (113, 'RDG', 'This is a permaculture company.', 'suppliers', 'Y 2017-01-01', 'in progress', NULL, 'mudiacom_soiltoil', '70', 'moneymakers offline', NULL, NULL);
INSERT INTO public.accounts VALUES (131, 'postmates', 'Deliver food for quick cash.', 'classes', 'Y 2017-01-01', 'in progress', NULL, 'mudiacom_soiltoil', '83', 'moneymaker earn extra', NULL, NULL);
INSERT INTO public.accounts VALUES (117, 'bay3', 'Workshop and temp storage for farm stuff. Tail Light Shop', 'lands', 'Y 2017-01-01', 'offline', NULL, 'mudiacom_soiltoil', '14', '', NULL, NULL);
INSERT INTO public.accounts VALUES (72, 'potting soil', 'Soil for planting seeds in trays. Bought by the yard.', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (73, 'compost', 'Organic matter that is added to the soil.', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (3, 'winter share revenue', 'see formula of csa revenue', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (35, 'pest control', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (37, 'greenhouse supplies', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (38, 'memberships and dues', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (41, 'soil ammendments', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (5, 'labor', 'Human power; seasonal labor; hired labor;', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (43, 'CSA crops purchased', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (45, 'greenhouse, LP heater', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (46, 'miscellaneous', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (47, 'organic certification', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (60, 'bags', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (14, 'greenhouse', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (44, 'fuel (for auto or truck)', 'The pump for gasoline.', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (137, 'house-gas-heat', NULL, NULL, 'Y 2017-07-10', 'in progress', NULL, NULL, NULL, 'budget monthly cash pay 50', NULL, NULL);
INSERT INTO public.accounts VALUES (138, 'house-cleaning', NULL, NULL, 'Y 2017-07-10', 'in progress', NULL, NULL, NULL, 'budget monthly cash pay 20', NULL, NULL);
INSERT INTO public.accounts VALUES (103, 'reseller-rbo', 'This is the idea that I am a webhosting reseller. This account serves to be a container for all of the economic transaction pertaining to webhosting reseller by the TLI rbo.', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (109, 'future funds', 'This is money that might be needed and is anyway budgeted here.', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (87, 'scene element', 'this is a substitute', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (90, 'labor for database administrator', 'work on database', 'databases', 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (57, 'tools', 'and miscellaneous supplies', 'tools', 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (124, '401K', 'Provided retirement plan. and the government sponsored savings method.', 'suppliers', 'Y 2017-01-01', 'in progress', NULL, 'mudiacom_soiltoil', '73', 'budget stock', NULL, NULL);
INSERT INTO public.accounts VALUES (125, 'mailbox', 'A place to receive postal mail.', 'suppliers', 'Y 2017-01-01', 'in progress', NULL, 'mudiacom_soiltoil', '75', 'budget pay 90 per six months', NULL, NULL);
INSERT INTO public.accounts VALUES (121, 'degree', 'My student loan.', 'processes', 'Y 2018-06-09', 'in progress', NULL, 'mudiacom_soiltoil', '131', 'get my house in order', NULL, NULL);
INSERT INTO public.accounts VALUES (134, 'house-cable', 'Pay my portion of the cable bill for internet access.', 'suppliers', 'Y 2018-07-14', 'pipeline', '', 'mudiacom_soiltoil', '86', 'budget pay 13 monthly cash', NULL, NULL);
INSERT INTO public.accounts VALUES (29, 'taxes', 'Files taxes every year at the beginning of the year for the previous year.', 'suppliers', 'Y 2018-07-14', 'pipeline', NULL, 'mudiacom_soiltoil', '88', 'budget quarterly', NULL, NULL);
INSERT INTO public.accounts VALUES (56, 'house-electricity', 'Pay my portion of the house electric bill. Keep track of the energy that I am using.', 'suppliers', 'Y 2018-07-14', 'pipeline', NULL, 'mudiacom_soiltoil', '87', 'budget monthly paypal pay 25', NULL, NULL);
INSERT INTO public.accounts VALUES (105, 'markets', 'Groceries. Food to eat. Try to make a routine out of going to the farmer''s markets.', 'suppliers', 'Y 2017-07-10', 'in progress', NULL, 'mudiacom_soil', '89', 'budget monthly cash pay 40', NULL, NULL);
INSERT INTO public.accounts VALUES (106, 'spacerent', 'This includes space rent.', 'projects', 'Y 2018-07-31', 'pipeline', NULL, 'mudiacom_soiltoil', '24', 'budget pay 40 monthly cash', NULL, NULL);
INSERT INTO public.accounts VALUES (114, 'Fresh Meadows', 'Organic cranberry sorting with online sales.', 'suppliers', 'Y 2017-01-01', 'in progress', NULL, 'mudiacom_soiltoil', '71', 'moneymakers earn in october', NULL, NULL);
INSERT INTO public.accounts VALUES (112, 'KB Partners', 'This is a freelance gig.', 'suppliers', 'Y 2017-01-01', 'offline', NULL, 'mudiacom_soiltoil', '61', 'work on it', NULL, NULL);
INSERT INTO public.accounts VALUES (67, 'land rent', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (68, 'marketing', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (92, 'design books', 'This includes booklets and 3-ring binders.', 'designs', 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (49, 'suppliers', 'Mixed organizations.', 'suppliers', 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (94, 'labor hyperlinks', 'The time it takes to surf and organize hyperlinks.', 'hyperlinks', 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (36, 'bank service charge', '', 'moneymakers', 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (95, 'labor - program applications', 'This is the programmer category.', 'applications', 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (96, 'books', 'These are the books.', 'books', 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (97, 'labor - programmer hours', '', 'classes', 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (71, 'professional services', 'These are the people whose services I hire.', 'designers', 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (99, 'budget for processes share', 'This is an aggregation for a process. This allows a scene_elements to take a share of a whole other processes.', 'processes', 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (101, 'budget for projects share', 'This allows a process to have a scene_elements that shares in a completely different project.', 'projects', 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (65, 'mortgage', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (18, 'conservation', 'IRS Form 8645', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (19, 'custom hire (machine work)', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (20, 'employee benefit program', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (22, 'lime', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (104, 'rt', 'This is a demand deposit bank account. The website is <a href="https://www.rocklandtrust.com/">www.rocklandtrust.com</a>. I use billpay to transfer funds to accounts cc. I use direct to deposit to receive funds from patagonia. I get cash from an atm. This is a CURRENT_ASSET. This is represented by a supplier.', 'suppliers', 'Y 2017-08-21', 'in progress', 'http://mudia.com/_images-v6/rt-logo.jpg', 'mudiacom_soiltoil', '69', 'budget stock', NULL, NULL);
INSERT INTO public.accounts VALUES (135, 'ebsb', NULL, 'suppliers', 'Y 2017-08-21', 'in progress', NULL, 'mudia_soiltoil', '82', 'budget stock', NULL, NULL);
INSERT INTO public.accounts VALUES (140, 'ebay', NULL, NULL, 'Y 2017-07-10', 'in progress', NULL, NULL, NULL, 'budget 0', NULL, NULL);
INSERT INTO public.accounts VALUES (23, 'freight and trucking', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (25, 'pension and profit-sharing', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (27, 'plants', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (30, 'utilities', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (93, 'budget for plant_lists', 'This is a tally that nets the revenue and expenses of a plant_lists.', 'plant_lists', 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (33, 'advertising', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (8, 'equipment', 'This includes tractor, oil, oil filter, installation, and repair. This includes purchase of equipment.', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (26, 'rent machinery', 'aka equipment rental', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (69, 'subscriptions', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (111, 'cash', 'paper money in the wallet and overflow safe place. atm on the map in the currency sense. and coins. and the whole process of cash in the money sense and unit of account sense.', 'processes', 'Y 2017-09-29', 'in progress', NULL, 'mudiacom_soiltoil', '185', 'budget stock', NULL, NULL);
INSERT INTO public.accounts VALUES (62, 'truck, expenses', 'includes oil changes and repairs', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (107, 'travel', 'This includes my train fare when I visit Dad in Florida.', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (86, 'internet service provider', 'get online', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (34, 'workshops', 'this includes all kinds of concepts including seminars, education, and classes', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (39, 'shipping fees and postage', 'The cost to send letters and ship packages.', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (9, 'fuel (for equipment)', 'Assuming this is fuel for the water pump or lawn mower or tractor or generator.', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (13, 'pumps and tanks', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (15, 'farmer income', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (76, 'moose tubers', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (77, 'packaging', 'containers for food (including wax boxes, bags, and rubber bands)', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (78, 'irrigation', 'equipment and resources that water the plants', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (79, 'farm stand rent', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (80, 'scale certification', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (81, 'tractor', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (82, 'volunteer welcoming', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (83, 'crops purchased', 'buying wholesale vegetables', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (84, 'soil testing', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (28, 'food storage', 'Preserving food via refrigeration, proper containers, ice, and warehousing.', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (2, 'wholesale revenue', 'This is revenue selling to non-members.', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (6, 'fertility', 'This includes manure, bagged fert, potting soil, straw mulch, cover crop seed.', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (7, 'seeds', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (10, 'biodiesel processor', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (11, 'DLCT land improvement', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (12, 'combine', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (48, 'repairs', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (50, 'sales', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (51, 'taxes, property', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (52, 'fertilizer', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (53, 'services', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (55, 'maintenance', '', NULL, 'Y 2017-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (91, 'computer equipment', 'Includes PCs and laptops.', 'suppliers', 'Y 2018-07-14', 'pipeline', NULL, NULL, '35', 'budget monthly from cc', NULL, NULL);
INSERT INTO public.accounts VALUES (1, 'CSA revenue', 'This is often based upon a formula dollars per share times number of shares.', NULL, 'Y 2018-01-01', 'offline', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (136, 'hosting2', NULL, 'suppliers', 'Y 2018-06-09', 'offline', NULL, NULL, '45', 'budget deducts 42 monthly from cc', NULL, NULL);
INSERT INTO public.accounts VALUES (66, 'interest expense', 'non-mortgage interest expense', NULL, 'Y 2021-01-01', '2021', NULL, NULL, NULL, NULL, 'true', NULL);
INSERT INTO public.accounts VALUES (89, 'registrar', 'This service enables the population of instances in the <em>domains</em> table. Use a service that is a supplier of domains. A service that registers a domain name and sells ssl certificates.', 'suppliers', 'Y 2017-08-21', 'pipeline', NULL, 'mudiacom_soiltoil', '58', 'budget deducts 96 scheduled from cc ', NULL, NULL);
INSERT INTO public.accounts VALUES (141, 'storage', NULL, NULL, 'Y 2021-01-01', '2021', NULL, NULL, NULL, NULL, 'true', NULL);
INSERT INTO public.accounts VALUES (85, 'hosting', 'Service on internet with computers serving up webpages via a webserver.
', 'suppliers', 'Y 2021-01-20', '2021', 'https://mudia.com/_images/album.png
', 'freerad2_frbfrb', '77', 'budget deducts 5 monthly from cc', 'true', NULL);
INSERT INTO public.accounts VALUES (42, 'phone', 'The talkie thingie that has invaded the social public platform. Be very careful and use it for positive information. Use it to test the FreeRadiantBunny app. This account also include Internet access because that is a phone company service.', 'tools', 'Y 2021-01-01', '2021', 'https://mudia.com/_images/album.png', 'mudiacom_soiltoil', '57', 'budget deducts 42 monthly from cc', 'true', NULL);
INSERT INTO public.accounts VALUES (4, 'room', 'Assuming that this is money paid for access to the land.', 'lands', 'Y 2021-01-01', '2021', 'https://mudia.com/_images/album.png', 'mudiacom_soiltoil', '146', 'budget monthly rt pay 636.67', 'true', NULL);
INSERT INTO public.accounts VALUES (142, 'repository', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (143, 'hosting', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts VALUES (144, 'email-hosting', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
