INSERT INTO public.markets VALUES (7, 'bitstamp', 'https://freeradiantbunny.org/_images/coins/bitstamp.png', 'exchange', 'Y 2020-09-06', 'pipeline', 'https://www.bitstamp.net/', 'bitstamp', NULL);
INSERT INTO public.markets VALUES (8, 'poloniex', 'https://freeradiantbunny.org/_images/coins/poloniex.png', 'exchange', 'Y 2020-09-06', 'pipeline', 'https://poloniex.com/', 'poloniex', NULL);
INSERT INTO public.markets VALUES (9, 'gatehub', 'https://freeradiantbunny.org/_images/coins/gatehub.png', 'exchange', 'Y 2020-09-06', NULL, 'https://gatehub.net/', 'gatehub', NULL);
INSERT INTO public.markets VALUES (11, 'bittrex', 'https://freeradiantbunny.org/_images/coins/bittrex.png', 'exchange', 'Y 2020-09-06', NULL, 'https://bittrex.com/', 'bittrex', NULL);
INSERT INTO public.markets VALUES (12, 'steemit', 'https://freeradiantbunny.org/_images/coins/steemit.png', 'blog', 'Y 2020-09-06', 'pipeline', 'https://steemit.com/@radiantbunny/feed', 'steemit', NULL);
INSERT INTO public.markets VALUES (3, 'herbfarm', 'https://freeradiantbunny.org/_images/herbfarm_logo.png', 'wallet', 'Y 2020-09-06', 'pipeline', 'https://electrum.org/', 'herbfarm', NULL);
INSERT INTO public.markets VALUES (15, 'binance.us', 'https://freeradiantbunny.org/_images/coins/bnb.png', 'exchange', 'Y 2020-11-29', NULL, 'https://www.binance.us/', 'binance.us', NULL);
INSERT INTO public.markets VALUES (10, 'coinbasepro', 'https://freeradiantbunny.org/_images/coins/coinbasepro.png', 'exchange', 'Y 2020-11-29', NULL, 'https://pro.coinbase.com/', 'coinbasepro', NULL);
INSERT INTO public.markets VALUES (2, 'gemini', 'https://freeradiantbunny.org/_images/coins/gemini.png', 'exchange', 'Y 2020-09-06', 'pipeline', 'https://exchange.gemini.com/', 'gemini', NULL);
INSERT INTO public.markets VALUES (4, 'kraken', 'https://freeradiantbunny.org/_images/coins/kraken.png', 'exchange', 'Y 2020-09-06', 'pipeline', 'https://www.kraken.com/en-us/', 'kraken', NULL);
INSERT INTO public.markets VALUES (5, 'exarpy', 'https://freeradiantbunny.org/_images/coins/exarpy.png', 'wallet', 'Y 2020-09-06', 'pipeline', 'https://exarpy.com/', 'exarpy', NULL);
INSERT INTO public.markets VALUES (16, 'uniswap', 'https://freeradiantbunny.org/_images/coins/uni.png', 'decentralized protocol', 'Y 2020-11-29', NULL, 'https://app.uniswap.org/', 'uniswap', NULL);
INSERT INTO public.markets VALUES (17, 'MetaMask', NULL, NULL, NULL, NULL, 'https://metamask.io', NULL, NULL);
INSERT INTO public.markets VALUES (6, 'binance', 'https://freeradiantbunny.org/_images/coins/bnb.png', 'exchange', 'Y 2020-12-10', 'pipeline', 'https://www.binance.com/en', 'binance', 'https://binance-docs.github.io/apidocs/spot/en/#general-info');
