INSERT INTO public.maxonomies VALUES (159, 'twitter', 'https://mudia.com/_images/twitter.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (189, 'describe unique features of land', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (119, 'search', 'https://freeradiantbunny.org/_images/search_stamp.png', '2021', 'Y 2021-01-05', '', '', '', 59, '');
INSERT INTO public.maxonomies VALUES (193, 'helpdesk', 'https://mudia.com/_images/documentation_stamp.png', NULL, 'Y 2020-12-30', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.maxonomies VALUES (194, 'classes', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', '2021', 'Y 2021-01-01', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.maxonomies VALUES (177, 'historical uses of land', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (178, 'describe kind of property surrounding property', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (8, 'subsection', 'https://mudia.com/_images/maxonomy/subsection.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (171, 'microclimate', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (196, 'album', 'https://mudia.com/_images/album.png', '2021', 'Y 2021-01-10', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.maxonomies VALUES (184, 'do any soil test results exist', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (185, 'does water drainage have any problems (such as web ground, standing water, water in the basement, etc)', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (186, 'are there any areas of soil loss or erosion', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (187, 'are there any areas that are too hot or too dry in teh summer', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (176, 'tax map, plot plan, or survey map of property', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (175, 'size of property', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (169, 'vegetation_and_wildlife', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (170, 'building_and_infrastructure', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (42, 'business_plan_texts', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (43, 'goal_statements', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (46, 'Design Methodology Statement', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (47, 'Homepage Screenprint', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (54, 'Results of Usability Testing', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (30, 'income_statement', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (27, 'gnucash', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (160, 'Pattern 1 from <em>A Pattern Language</em>, by Christopher Alexander, et al.', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-31', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (37, 'materials flow plan', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (38, 'sample schedule', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (39, 'concept map', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (183, 'describe the type of soil (clay, sandy, loamy, rocky)', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (166, 'water', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (14, 'blogpost', 'https://mudia.com/_images/blogpost_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (179, 'describe number and type of buildings on land', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (180, 'does property have desirable views', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (164, 'climate', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (167, 'legal_issues', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (168, 'access_and_circulation', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (163, 'user documentation', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (52, 'Design Theories Supporting', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (197, 'moneymaker', 'https://mudia.com/_images/corp_scout_stock.png', '2021', 'Y 2021-01-10', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.maxonomies VALUES (191, 'are there any site challenges', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (181, 'does property have undesirable views', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (162, 'Web Site Project Management', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (172, 'zones_of_use', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (173, 'soils', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (165, 'landform', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (33, 'social_network', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (190, 'set septic across field', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (5, '_styles', 'https://mudia.com/_images/maxonomy/_styles.png', '2021', 'Y 2021-01-08', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (129, 'domain name', 'https://mudia.com/_images/wright_brothers.png', '2021', 'Y 2021-01-10', 'also include DNS, ssl certificates, subdomain, and other domain_name technology ', '', '', 70, '');
INSERT INTO public.maxonomies VALUES (44, 'budgets', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (17, 'design_instance', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (18, 'processes', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (101, 'tags', 'https://mudia.com/_images/dash/stamp_tagging.png', '2021', 'Y 2021-01-01', '', '', '', 35, '');
INSERT INTO public.maxonomies VALUES (20, 'whoihelp', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (23, 'work_crew', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (7, 'application', 'https://mudia.com/_images/maxonomy/application.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (153, 'redirect', 'https://mudia.com/_images/maxonomy/redirect.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (157, 'xml', 'https://mudia.com/_images/maxonomy/symbolic_link.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (41, 'dashboard', 'https://mudia.com/_images/dash/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (4, '_images', 'https://mudia.com/_images/maxonomy/_images.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (29, 'supplier', 'https://mudia.com/_images/documentation_stamp.png', '2021', 'Y 2021-01-10', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (53, 'What Would Krug Say?', 'https://mudia.com/_images/dash/use_cases_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (51, 'Use Cases', 'https://mudia.com/_images/dash/use_cases_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (2, 'favicon', 'https://mudia.com/_images/maxonomy/favicon.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (26, 'pickup_values', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (40, 'calendar and timeline', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (56, 'Website Infrastructure Overview', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (55, 'Design Plan for Cascading Style Sheets', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (57, 'Design Plan for Images', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (50, 'Persona List', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (15, 'php', 'https://mudia.com/_images/maxonomy/application.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (12, 'symbolic_link', 'https://mudia.com/_images/maxonomy/symbolic_link.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (154, 'admin', 'https://mudia.com/_images/administrative_dashboard.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (9, 'homepage', 'https://mudia.com/_images/maxonomy/homepage_stamp_spaceship_earth.png', '2021', 'Y 2021-01-01', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (142, 'about', 'https://mudia.com/_images/dash/about_stamp.png', '2021', 'Y 2021-01-01', '', '', '', 81, '');
INSERT INTO public.maxonomies VALUES (11, 'schema', 'https://mudia.com/_images/schema.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (155, '404 File Not Found', 'https://freeradiantbunny.org/_images/404_logo.png', '', 'Y 2020-12-30', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (48, 'Homepage Wireframe', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (28, '_backup', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (24, 'project_seasons', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (36, 'monthly tasks schedule', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (35, 'site assessment and analysis', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (1, 'webpage', 'https://mudia.com/_images/documentation_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (156, 'contact', 'https://mudia.com/_images/dash/contact_stamp.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (79, 'reflector', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 20, '');
INSERT INTO public.maxonomies VALUES (80, 'collaborative editing', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 53, '');
INSERT INTO public.maxonomies VALUES (81, 'community guidelines', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 82, '');
INSERT INTO public.maxonomies VALUES (82, 'sign out', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 9, '');
INSERT INTO public.maxonomies VALUES (113, 'project management', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 51, '');
INSERT INTO public.maxonomies VALUES (109, 'comments', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 45, '');
INSERT INTO public.maxonomies VALUES (83, 'invitations', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 11, '');
INSERT INTO public.maxonomies VALUES (86, 'onboarding', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 14, '');
INSERT INTO public.maxonomies VALUES (102, 'collectible achievements', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 30, '');
INSERT INTO public.maxonomies VALUES (92, 'buddy list', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 24, '');
INSERT INTO public.maxonomies VALUES (108, 'five star ratings', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 44, '');
INSERT INTO public.maxonomies VALUES (85, 'authorize', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 12, '');
INSERT INTO public.maxonomies VALUES (75, 'welcome area', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 15, '');
INSERT INTO public.maxonomies VALUES (89, 'testimonials', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 18, '');
INSERT INTO public.maxonomies VALUES (91, 'availability', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 23, '');
INSERT INTO public.maxonomies VALUES (133, 'rating &amp; polling', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 52, '');
INSERT INTO public.maxonomies VALUES (136, 'badges', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 74, '');
INSERT INTO public.maxonomies VALUES (137, 'activity stream', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 26, '');
INSERT INTO public.maxonomies VALUES (138, 'webserver infrastructure', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 85, '');
INSERT INTO public.maxonomies VALUES (141, 'site identity', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 83, '');
INSERT INTO public.maxonomies VALUES (150, 'upload &amp; download files', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 75, '');
INSERT INTO public.maxonomies VALUES (69, 'sign in (aka login)', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 8, '');
INSERT INTO public.maxonomies VALUES (103, 'send this', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 38, '');
INSERT INTO public.maxonomies VALUES (104, 'lifecycle', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 40, '');
INSERT INTO public.maxonomies VALUES (105, 'terms of service', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 41, '');
INSERT INTO public.maxonomies VALUES (106, 'vote to promote', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 42, '');
INSERT INTO public.maxonomies VALUES (152, 'development report', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 87, '');
INSERT INTO public.maxonomies VALUES (66, 'self-deprecating error messages', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 3, '');
INSERT INTO public.maxonomies VALUES (3, 'robots.txt', 'https://mudia.com/_images/robots.txt.png', '', 'Y 2020-12-22', '', '', '', NULL, '');
INSERT INTO public.maxonomies VALUES (107, 'thumbs up and thumbs down ratings', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 43, '');
INSERT INTO public.maxonomies VALUES (111, 'forum moderation', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 49, '');
INSERT INTO public.maxonomies VALUES (114, 'edit this page', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 54, '');
INSERT INTO public.maxonomies VALUES (115, 'crowd sourcing', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 55, '');
INSERT INTO public.maxonomies VALUES (67, 'ask questions', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 4, '');
INSERT INTO public.maxonomies VALUES (68, 'your versus mine', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 5, '');
INSERT INTO public.maxonomies VALUES (116, 'following', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 56, '');
INSERT INTO public.maxonomies VALUES (118, 'recommendations', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 58, '');
INSERT INTO public.maxonomies VALUES (120, 'conversational search', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 60, '');
INSERT INTO public.maxonomies VALUES (124, 'grow organically', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 65, '');
INSERT INTO public.maxonomies VALUES (125, 'collaborative filtering', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 66, '');
INSERT INTO public.maxonomies VALUES (126, 'report abuse', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 67, '');
INSERT INTO public.maxonomies VALUES (65, 'conversation', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 2, '');
INSERT INTO public.maxonomies VALUES (117, 'filtering', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 57, '');
INSERT INTO public.maxonomies VALUES (74, 'private beta', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 13, '');
INSERT INTO public.maxonomies VALUES (112, 'private conversation', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 50, '');
INSERT INTO public.maxonomies VALUES (149, 'site hierarchy', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 91, '');
INSERT INTO public.maxonomies VALUES (121, 'find people', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 61, '');
INSERT INTO public.maxonomies VALUES (59, 'total number of members', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 1, '');
INSERT INTO public.maxonomies VALUES (145, 'user area', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 93, '');
INSERT INTO public.maxonomies VALUES (60, 'find with tags', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 36, '');
INSERT INTO public.maxonomies VALUES (146, 'access logs and web server statistics', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 84, '');
INSERT INTO public.maxonomies VALUES (148, 'teases', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 92, '');
INSERT INTO public.maxonomies VALUES (62, 'groups', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 64, '');
INSERT INTO public.maxonomies VALUES (63, 'rss feeds', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 77, '');
INSERT INTO public.maxonomies VALUES (64, 'membership roster', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 78, '');
INSERT INTO public.maxonomies VALUES (71, 'plan events', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 80, '');
INSERT INTO public.maxonomies VALUES (73, 'attribution', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 21, '');
INSERT INTO public.maxonomies VALUES (110, 'licensing', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 47, '');
INSERT INTO public.maxonomies VALUES (78, 'sign-in continuity', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 10, '');
INSERT INTO public.maxonomies VALUES (84, 'avatars', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 22, '');
INSERT INTO public.maxonomies VALUES (87, 'wireframes', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 89, '');
INSERT INTO public.maxonomies VALUES (88, 'profile', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 17, '');
INSERT INTO public.maxonomies VALUES (90, 'personal dashboard', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 19, '');
INSERT INTO public.maxonomies VALUES (93, 'microblogging', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 25, '');
INSERT INTO public.maxonomies VALUES (94, 'user gallery', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 27, '');
INSERT INTO public.maxonomies VALUES (76, 'reengagement', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 16, '');
INSERT INTO public.maxonomies VALUES (147, 'footer', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 94, '');
INSERT INTO public.maxonomies VALUES (127, 'mbrowsable', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 69, '');
INSERT INTO public.maxonomies VALUES (95, 'named levels', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 28, '');
INSERT INTO public.maxonomies VALUES (96, 'reputation labels', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 29, '');
INSERT INTO public.maxonomies VALUES (97, 'rankings', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 31, '');
INSERT INTO public.maxonomies VALUES (98, 'favorite', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 33, '');
INSERT INTO public.maxonomies VALUES (99, 'saving', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 32, '');
INSERT INTO public.maxonomies VALUES (100, 'displaying', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 34, '');
INSERT INTO public.maxonomies VALUES (143, 'blog', 'https://mudia.com/_images/dash/ocm_stamp.png', '2021', 'Y 2021-02-22', 'has blogposts rows', 'media', 'count blogposts rows', 39, '');
INSERT INTO public.maxonomies VALUES (151, 'site map', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 90, '');
INSERT INTO public.maxonomies VALUES (70, 'sign-up or registration', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 7, '');
INSERT INTO public.maxonomies VALUES (72, 'forum', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 48, '');
INSERT INTO public.maxonomies VALUES (123, 'circles of connections', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 63, '');
INSERT INTO public.maxonomies VALUES (128, 'reviews', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 46, '');
INSERT INTO public.maxonomies VALUES (144, 'chat', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 79, '');
INSERT INTO public.maxonomies VALUES (130, 'hyperlinks', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 71, '');
INSERT INTO public.maxonomies VALUES (132, 'subject matter', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 73, '');
INSERT INTO public.maxonomies VALUES (135, 'video embedding', 'https://mudia.com/_images/dash/ocm_stamp.png', '', 'Y 2020-12-22', '', '', '', 76, '');
