INSERT INTO public.moneymaker_measurements VALUES (42, 'Chainlink adaptor', 'ok', 'Adaptor', 'unknown', NULL, 'deploy()', NULL, NULL, 17);
INSERT INTO public.moneymaker_measurements VALUES (43, 'Chainlink bridge', 'ok', 'Chainlink node', 'unknown', NULL, 'submit_form()', NULL, NULL, 22);
INSERT INTO public.moneymaker_measurements VALUES (44, 'IOT and API', 'ok', 'physical + API', 'unknown', NULL, 'install', NULL, NULL, 16);
INSERT INTO public.moneymaker_measurements VALUES (48, 'on-chain service agreement', 'ok', 'smart contract', NULL, NULL, 'guarantee', NULL, NULL, 39);
INSERT INTO public.moneymaker_measurements VALUES (29, 'Chainlink job', 'ok', 'Job', 'unknown', NULL, 'invokeAdaptor()', NULL, NULL, 30);
INSERT INTO public.moneymaker_measurements VALUES (28, 'Chainlink node', 'ok', 'Chainlink node', 'unknown', NULL, 'emitOrderRequest()', NULL, NULL, 29);
INSERT INTO public.moneymaker_measurements VALUES (41, 'Chainlink oracle', 'ok', 'smart contract', 'unknown', NULL, 'controlPunativeNodeLockup()', NULL, NULL, 37);
INSERT INTO public.moneymaker_measurements VALUES (18, 'Chainlink oracle', 'ok', 'smart contract', '0', NULL, 'setFulfillmentPermission()', NULL, '0.000043813 ETH', 19);
INSERT INTO public.moneymaker_measurements VALUES (33, 'Chainlink adaptor', 'ok', 'Adaptor', 'unknown', NULL, 'sendAnswerCallback()', NULL, NULL, 34);
INSERT INTO public.moneymaker_measurements VALUES (30, 'Chainlink adaptor', 'ok', 'Adaptor', 'unknown', NULL, 'getData()', NULL, NULL, 31);
INSERT INTO public.moneymaker_measurements VALUES (39, '', 'offline', 'BLOCKCHAIN', 'unknown', NULL, 'free-service', NULL, NULL, NULL);
INSERT INTO public.moneymaker_measurements VALUES (20, 'github', 'ok', 'smart contract', 'balance=100 LINK', NULL, 'receive', NULL, '0', 21);
INSERT INTO public.moneymaker_measurements VALUES (31, 'IOT and API', 'ok', 'physical + IDE', 'amortize', NULL, 'measureAndReturnAnswer()', NULL, NULL, 32);
INSERT INTO public.moneymaker_measurements VALUES (14, 'Chainlink oracle', 'ok', 'smart contract', 'get_dev_cost()<br />get_txn_cost()', NULL, 'deploy()<br />stock', NULL, '0.00109133 ETH', 18);
INSERT INTO public.moneymaker_measurements VALUES (19, 'stake oracle', 'ok', 'wallet', '100 LINK out', NULL, 'send()', NULL, '? ETH', 20);
INSERT INTO public.moneymaker_measurements VALUES (7, 'Ropsten Ethereum Faucet', 'ok', 'faucet', '1 ETH in', NULL, 'submit-form', NULL, '0', 7);
INSERT INTO public.moneymaker_measurements VALUES (11, 'ETH in MetaMask', 'ok', 'wallet balance', '0', NULL, 'stock', NULL, '0', 11);
INSERT INTO public.moneymaker_measurements VALUES (16, 'github', 'ok', 'repository', '0', NULL, 'free-code', '_LINK=[row-15-address]', '0', 14);
INSERT INTO public.moneymaker_measurements VALUES (5, 'Chainlink faucet Ropsten', 'ok', 'faucet', '100 LINK in', 'no', 'free-service', NULL, '0', 5);
INSERT INTO public.moneymaker_measurements VALUES (26, 'Chainlink job', 'ok', 'json config file', '0', NULL, 'ID-assigned', NULL, '0', 24);
INSERT INTO public.moneymaker_measurements VALUES (6, 'LINK balance Ropsten', 'ok', 'Ropsten block explorer', '0', NULL, 'stock', NULL, '0', 6);
INSERT INTO public.moneymaker_measurements VALUES (40, 'LINK contract Mainnet', 'offline', 'smart contract', 'unknown', NULL, 'free-contract', NULL, NULL, NULL);
INSERT INTO public.moneymaker_measurements VALUES (8, 'ETH balance Ropsten', 'ok', 'Ropsten block explorer', '0', NULL, 'stock', NULL, '0', 8);
INSERT INTO public.moneymaker_measurements VALUES (22, 'Chainlinked contract', 'ok', 'smart contract', '0', NULL, 'deploy()', NULL, '0', 25);
INSERT INTO public.moneymaker_measurements VALUES (36, 'namecheap.com', 'ok', 'domain_name', '12-USD-per-year', NULL, 'pay-yearly', NULL, NULL, 0);
INSERT INTO public.moneymaker_measurements VALUES (37, 'VPN', 'ok', 'VPN', 'unknown', NULL, NULL, NULL, NULL, -2);
INSERT INTO public.moneymaker_measurements VALUES (38, 'namecheap.com', 'ok', 'Secure DNS', 'unknown', NULL, NULL, NULL, NULL, -1);
INSERT INTO public.moneymaker_measurements VALUES (21, 'measurement recorder', 'ok', 'Adaptor', '5-USD-monthly', NULL, 'compile measurements', NULL, '0', 33);
INSERT INTO public.moneymaker_measurements VALUES (47, 'joan jett script', 'ok', 'bot', 'unknown', NULL, 'measure reputation', NULL, NULL, 38);
INSERT INTO public.moneymaker_measurements VALUES (2, 'fiew.io', 'ok', 'Ethereum node', '20-USD-monthly', 'yes', 'pay-monthly', NULL, '0.006 USD per job', 2);
INSERT INTO public.moneymaker_measurements VALUES (10, 'LINK in MetaMask', 'ok', 'wallet balance', '0', NULL, 'stock', NULL, '0', 10);
INSERT INTO public.moneymaker_measurements VALUES (9, 'MetaMask Wallet', 'ok', 'wallet', 'free-software', NULL, 'free-software', NULL, '0', 9);
INSERT INTO public.moneymaker_measurements VALUES (12, 'postgresql', 'ok', 'database', '2020-USD-monthly', NULL, 'pay-monthly', NULL, 'capacity?', 12);
INSERT INTO public.moneymaker_measurements VALUES (17, 'remix.ethereum.org', 'ok', 'IDE', '0', NULL, 'free-website', NULL, '0', 15);
INSERT INTO public.moneymaker_measurements VALUES (27, 'Chainlink oracle', 'ok', 'smart contract', 'unknown', NULL, 'publishEvent()', NULL, NULL, 27);
INSERT INTO public.moneymaker_measurements VALUES (45, 'Chainlink node', 'ok', 'Chainlink node', 'unknown', NULL, 'watchForEvents()', NULL, NULL, 28);
INSERT INTO public.moneymaker_measurements VALUES (46, 'Chainlink node', 'ok', 'Chainlink node', 'unknown', NULL, 'sendAnswerCallback()', NULL, NULL, 35);
INSERT INTO public.moneymaker_measurements VALUES (1, 'Ropsten Testnet', 'ok', 'BLOCKCHAIN', '0', 'no', 'free-service', NULL, '0', 1);
INSERT INTO public.moneymaker_measurements VALUES (15, 'LINK contract address Ropsten', 'ok', 'smart contract', '0', NULL, 'free-contract', NULL, '0', 3);
INSERT INTO public.moneymaker_measurements VALUES (13, 'Chainlink node', 'ok', 'virtual server', '5-USD-monthly', NULL, 'pay-monthly', NULL, 'capacity?', 13);
INSERT INTO public.moneymaker_measurements VALUES (4, 'Nifty Wallet', 'ok', 'wallet', '0', NULL, 'free-software', NULL, '0', 4);
INSERT INTO public.moneymaker_measurements VALUES (35, 'Chainlink contract', 'ok', 'smart contract', 'unknown', NULL, 'receiveAnswer()', NULL, '', 36);
INSERT INTO public.moneymaker_measurements VALUES (24, 'Chainlink contract', 'ok', 'smart contract', '0', NULL, 'transferAndCall()', NULL, '? ETH', 26);
INSERT INTO public.moneymaker_measurements VALUES (25, 'Chainlink node operator', 'ok', 'the operator', '0', NULL, 'NewJob form', NULL, 'operator-wages', 23);
