INSERT INTO public.permaculture_topics VALUES (25, 'Earthworks and Windbreaks', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (16, 'Design Presentation', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (15, 'Income From Acres', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (1, 'Introduction to Permaculture', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (19, 'Climate and Microclimate', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (23, 'Design for Disaster', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (11, 'Maps and Documentation', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (17, 'Land Access and Land Ownership', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (24, 'Biotechnology', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (18, 'Landform (Topography)', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (26, 'Communities', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (12, 'Design Graphics', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (13, 'Site Analysis', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (6, 'Legal Structures', NULL, 'pipeline', 'Y 2018-10-12', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (5, 'Economics and Investment', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (7, 'Cosmology', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (3, 'Ethics and Principles', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (9, 'Creative Problem Solving', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (2, 'Design Science', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (27, 'Suburban Permaculture', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (10, 'Patterns Literacy', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (37, 'sectors', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (21, 'Water', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (8, 'Methods of Design', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (31, 'Zone 0', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (20, 'Soils and the Web of Life', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (14, 'Zones and Sectors', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (33, 'Zone II', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (28, 'Urban Permaculture', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (30, 'Zone 00', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (29, 'Village Permamculture', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (32, 'Zone I', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (22, 'Siting and Placement', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (4, 'Principles of Ecology', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (34, 'Zone III', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (35, 'Zone IV', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
INSERT INTO public.permaculture_topics VALUES (36, 'Zone V', NULL, 'pipeline', 'Y 2018-08-14', 'https://mudia.com/_images/permaculture_one_cover.png');
