INSERT INTO public.plant_attributes VALUES (2, 3, 'culinary herb', 'minty flavor');
INSERT INTO public.plant_attributes VALUES (3, 3, 'habit', 'run');
INSERT INTO public.plant_attributes VALUES (4, 3, 'tea', 'Excellent');
INSERT INTO public.plant_attributes VALUES (5, 3, 'medicinal', 'Good');
INSERT INTO public.plant_attributes VALUES (6, 3, 'wildlife', 'provides food');
INSERT INTO public.plant_attributes VALUES (7, 3, 'moisture', 'Mesic');
INSERT INTO public.plant_attributes VALUES (8, 3, 'use', 'Aromic Pest Confuser');
INSERT INTO public.plant_attributes VALUES (9, 3, 'edible', 'edible flowers');
INSERT INTO public.plant_attributes VALUES (10, 88, 'edible greens', 'Good');
INSERT INTO public.plant_attributes VALUES (11, 88, 'medicinal', 'Fair');
INSERT INTO public.plant_attributes VALUES (1, 146, 'medicinal', 'Excellent');
INSERT INTO public.plant_attributes VALUES (13, 88, 'nectory', 'Generalist Nectory');
INSERT INTO public.plant_attributes VALUES (12, 88, 'invertebrates shelter', 'food and shelter');
INSERT INTO public.plant_attributes VALUES (14, 90, 'edible greens', 'Excellent');
INSERT INTO public.plant_attributes VALUES (15, 90, 'culinary', 'Excellent');
INSERT INTO public.plant_attributes VALUES (16, 90, 'medicinal', 'Superfood');
INSERT INTO public.plant_attributes VALUES (17, 90, 'dynamic accumulator', 'Yes');
INSERT INTO public.plant_attributes VALUES (18, 90, 'nectory', 'Generalist Nectory');
INSERT INTO public.plant_attributes VALUES (19, 90, 'ground cover', 'Yes');
INSERT INTO public.plant_attributes VALUES (20, 90, 'use', 'Aromic Pest Confuser');
INSERT INTO public.plant_attributes VALUES (21, 146, 'medicinal', 'Excellent');
INSERT INTO public.plant_attributes VALUES (22, 146, 'dynamic accumulator', 'Yes');
INSERT INTO public.plant_attributes VALUES (23, 146, 'nectory', 'Generalist Nectory');
INSERT INTO public.plant_attributes VALUES (24, 146, 'invertebrates shelter', 'Generalist Nectory');
INSERT INTO public.plant_attributes VALUES (25, 146, 'drawbacks', 'poison');
INSERT INTO public.plant_attributes VALUES (26, 100, 'use', 'Aromic Pest Confuser');
INSERT INTO public.plant_attributes VALUES (27, 94, 'use', 'Aromic Pest Confuser');
INSERT INTO public.plant_attributes VALUES (28, 190, 'use', 'Aromic Pest Confuser');
INSERT INTO public.plant_attributes VALUES (29, 189, 'use', 'Aromic Pest Confuser');
INSERT INTO public.plant_attributes VALUES (30, 98, 'use', 'Aromic Pest Confuser');
INSERT INTO public.plant_attributes VALUES (31, 178, 'edible', 'delicious common fruit');
INSERT INTO public.plant_attributes VALUES (32, 77, 'edible', 'delicious berries');
INSERT INTO public.plant_attributes VALUES (33, 180, 'edible', 'native passionfruit');
INSERT INTO public.plant_attributes VALUES (34, 181, 'edible', 'young pods and seeds cooked');
INSERT INTO public.plant_attributes VALUES (35, 147, 'edible greens', 'cook young greens');
INSERT INTO public.plant_attributes VALUES (36, 147, 'drawbacks', 'stinging');
INSERT INTO public.plant_attributes VALUES (37, 182, 'edible', 'edible tubors');
INSERT INTO public.plant_attributes VALUES (38, 94, 'edible', 'lemony minty flavor');
INSERT INTO public.plant_attributes VALUES (39, 94, 'edible', 'tea');
INSERT INTO public.plant_attributes VALUES (40, 180, 'edible', 'tea');
INSERT INTO public.plant_attributes VALUES (41, 98, 'edible', 'tea');
INSERT INTO public.plant_attributes VALUES (42, 90, 'edible', 'edible flowers');
INSERT INTO public.plant_attributes VALUES (43, 183, 'drawbacks', 'poison');
INSERT INTO public.plant_attributes VALUES (44, 182, 'edible', 'edible seeds');
INSERT INTO public.plant_attributes VALUES (45, 170, 'drawbacks', 'leaves and flowers toxic in large quantities');
INSERT INTO public.plant_attributes VALUES (46, 179, 'use', 'insect repellent');
INSERT INTO public.plant_attributes VALUES (47, 186, 'nectory', 'attracts butterflies');
INSERT INTO public.plant_attributes VALUES (48, 184, 'nectory', 'attracts butterflies');
INSERT INTO public.plant_attributes VALUES (49, 184, 'nectory', 'attracts pollinators');
INSERT INTO public.plant_attributes VALUES (50, 184, 'drawbacks', 'sap contains toxic chemicals');
INSERT INTO public.plant_attributes VALUES (51, 183, 'nectory', 'attracts bees and wasps');
INSERT INTO public.plant_attributes VALUES (52, 183, 'use', 'detracts wireworms');
INSERT INTO public.plant_attributes VALUES (53, 112, 'culinary', 'seasoning');
INSERT INTO public.plant_attributes VALUES (54, 187, 'medicinal', 'many traditional uses');
INSERT INTO public.plant_attributes VALUES (55, 188, 'medicinal', 'several uses');
INSERT INTO public.plant_attributes VALUES (57, 187, 'use', 'detracts voles');
INSERT INTO public.plant_attributes VALUES (58, 185, 'medicinal', 'traditional uses');
INSERT INTO public.plant_attributes VALUES (59, 185, 'nectory', 'attracts butterflies');
INSERT INTO public.plant_attributes VALUES (60, 186, 'use', 'nitrogen fixer');
INSERT INTO public.plant_attributes VALUES (61, 183, 'native', 'yes');
INSERT INTO public.plant_attributes VALUES (62, 185, 'native', 'yes');
INSERT INTO public.plant_attributes VALUES (63, 77, 'native', 'yes');
INSERT INTO public.plant_attributes VALUES (64, 147, 'native', 'yes');
INSERT INTO public.plant_attributes VALUES (65, 184, 'native', 'yes');
INSERT INTO public.plant_attributes VALUES (66, 100, 'native', 'yes');
INSERT INTO public.plant_attributes VALUES (67, 228, 'sow', 'Sow seeds in situ in autumn');
INSERT INTO public.plant_attributes VALUES (68, 100, 'category', 'perennial');
INSERT INTO public.plant_attributes VALUES (69, 212, 'propogation', 'bulbs');
INSERT INTO public.plant_attributes VALUES (70, 160, 'zone', 'zone 5 ok');
INSERT INTO public.plant_attributes VALUES (71, 160, 'sun', 'full sun');
INSERT INTO public.plant_attributes VALUES (72, 160, 'sow', 'plant early to late spring');
INSERT INTO public.plant_attributes VALUES (73, 160, 'category', 'perennial');
INSERT INTO public.plant_attributes VALUES (74, 211, 'cultivate', 'deadhead');
INSERT INTO public.plant_attributes VALUES (75, 211, 'sun', 'sunny');
INSERT INTO public.plant_attributes VALUES (76, 210, 'size', 'Very Large Flower Size');
INSERT INTO public.plant_attributes VALUES (77, 66, 'sun', 'Sun, but tolerates shade');
INSERT INTO public.plant_attributes VALUES (78, 66, 'when', 'Sow seeds of annuals in spring');
INSERT INTO public.plant_attributes VALUES (79, 67, 'sun', 'full sun');
INSERT INTO public.plant_attributes VALUES (80, 67, 'sow', 'surface sow');
INSERT INTO public.plant_attributes VALUES (81, 67, 'sow', 'do not cover seeds because they need light');
INSERT INTO public.plant_attributes VALUES (82, 67, 'water', 'do not overhead water');
INSERT INTO public.plant_attributes VALUES (83, 69, 'sun', 'full sun');
INSERT INTO public.plant_attributes VALUES (84, 69, 'water', 'drought resistant');
INSERT INTO public.plant_attributes VALUES (85, 69, 'sow', 'start indoors 8 weeks before last frost');
INSERT INTO public.plant_attributes VALUES (86, 209, 'propogate', 'bulbs');
INSERT INTO public.plant_attributes VALUES (87, 239, 'sow', 'sow seeds in spring');
INSERT INTO public.plant_attributes VALUES (88, 239, 'sun', 'full sun');
INSERT INTO public.plant_attributes VALUES (89, 239, 'sow', 'bulbs');
INSERT INTO public.plant_attributes VALUES (90, 234, 'sow', 'sow ripe seed');
INSERT INTO public.plant_attributes VALUES (91, 234, 'sun', 'full sun or partial shade');
INSERT INTO public.plant_attributes VALUES (92, 240, 'category', 'hardy annual');
INSERT INTO public.plant_attributes VALUES (93, 241, 'sun', 'full sun or partial shade');
INSERT INTO public.plant_attributes VALUES (94, 241, 'propogation', 'propagate via tubers and rhizome in fall');
INSERT INTO public.plant_attributes VALUES (95, 243, 'origin', 'native to Northeast');
INSERT INTO public.plant_attributes VALUES (96, 236, 'category', 'perennial');
INSERT INTO public.plant_attributes VALUES (97, 89, 'propagation', 'sow direct in Spring');
INSERT INTO public.plant_attributes VALUES (98, 106, 'cultivation', 'deadhead');
INSERT INTO public.plant_attributes VALUES (99, 245, 'propagation', 'plant bulbs in early Spring');
INSERT INTO public.plant_attributes VALUES (100, 245, 'color', 'white flowers');
INSERT INTO public.plant_attributes VALUES (101, 175, 'water', 'tolerates drought');
INSERT INTO public.plant_attributes VALUES (102, 175, 'cultivation', 'pinch old flowerheads');
INSERT INTO public.plant_attributes VALUES (103, 242, 'category', 'perennial');
INSERT INTO public.plant_attributes VALUES (104, 248, 'propagation', 'propogate by stem and leaf cuttings; division or seed');
INSERT INTO public.plant_attributes VALUES (105, 249, 'propagation', 'start indors six weeks before last frost');
INSERT INTO public.plant_attributes VALUES (106, 250, 'sun', 'full sun or partial shade');
INSERT INTO public.plant_attributes VALUES (107, 250, 'zone', 'zone 5 ok');
INSERT INTO public.plant_attributes VALUES (108, 250, 'when', 'plant in late spring and early fall');
INSERT INTO public.plant_attributes VALUES (110, 197, 'propagation', 'plant in early to late spring or late fall');
INSERT INTO public.plant_attributes VALUES (111, 229, 'propagation', 'plant in midspring');
INSERT INTO public.plant_attributes VALUES (112, 229, 'propagation', 'tolerates light frost');
INSERT INTO public.plant_attributes VALUES (113, 212, 'propagation', 'Seperate offsets the corms when you lift them in autumn');
INSERT INTO public.plant_attributes VALUES (114, 59, 'propagation', 'start indoors 8 weeks before last frost');
INSERT INTO public.plant_attributes VALUES (115, 226, 'propagation', 'Seed can be sown in pots under glass in spring or autumn');
INSERT INTO public.plant_attributes VALUES (116, 58, 'propogation', 'sow seeds underglass in spring');
INSERT INTO public.plant_attributes VALUES (117, 58, 'sun', 'full sun');
INSERT INTO public.plant_attributes VALUES (118, 58, 'water', 'keep well watered');
INSERT INTO public.plant_attributes VALUES (119, 224, 'sun', 'full sun');
INSERT INTO public.plant_attributes VALUES (120, 224, 'propogation', 'direct seed after last front');
INSERT INTO public.plant_attributes VALUES (121, 260, 'origin', 'native to Northeast');
INSERT INTO public.plant_attributes VALUES (122, 105, 'propagation', 'start indoors 6 weeks before last frost');
