INSERT INTO public.plant_aliases VALUES (1, 2, 'Bean, Snap');
INSERT INTO public.plant_aliases VALUES (2, 74, 'Pea, Soup');
INSERT INTO public.plant_aliases VALUES (1, 212, 'Acidanthera');
INSERT INTO public.plant_aliases VALUES (2, 89, 'Marigold');
INSERT INTO public.plant_aliases VALUES (3, 228, 'spine acanthus');
INSERT INTO public.plant_aliases VALUES (4, 220, 'Orange Coneflower');
INSERT INTO public.plant_aliases VALUES (5, 54, 'Bluemink');
INSERT INTO public.plant_aliases VALUES (6, 265, 'Cramp Bark');
INSERT INTO public.plant_aliases VALUES (1, 2, 'Bean, Snap');
INSERT INTO public.plant_aliases VALUES (2, 74, 'Pea, Soup');
