INSERT INTO public.subsystems VALUES (35, 'Aggregator Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (36, 'Budgets Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (37, 'CSA Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (38, 'Communications Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (39, 'Database Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (40, 'Design Method Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (41, 'Graphics Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (42, 'Identity Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (43, 'Inquiring System Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (44, 'Knowledge Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (45, 'Lands Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (46, 'Library Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (47, 'Markets Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (48, 'Markup Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (49, 'Motivational Model Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (50, 'Plant Lists Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (51, 'Search Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (52, 'Security Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (53, 'Shipper Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (54, 'Sound Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (55, 'Stakeholder Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (56, 'Standards Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (57, 'System Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (58, 'Time Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
INSERT INTO public.subsystems VALUES (59, 'Websites Subsystem', NULL, 'Y 2022-03-02', '2022', 'https://freeradiantbunny.org/_images/pf_logo_stamp.png', NULL, NULL, NULL);
