INSERT INTO public.units VALUES (7, 'row foot', 'A linear distance.');
INSERT INTO public.units VALUES (4, 'head', 'Example: lettuce.');
INSERT INTO public.units VALUES (3, 'each', 'Single plant or harvested single plant part.');
INSERT INTO public.units VALUES (2, 'bunch', 'Bound by a rubber band.');
INSERT INTO public.units VALUES (5, 'pint', 'Volume.');
INSERT INTO public.units VALUES (8, '100 square-foot', 'Area. From Jeavons HTGMV page 86-96.');
INSERT INTO public.units VALUES (11, 'wind speed (feet per second)', 'a measurement of how fast the wind is travelling');
INSERT INTO public.units VALUES (12, 'lumens', 'a measurement of how much light is shining');
INSERT INTO public.units VALUES (13, 'moisture', 'a measurement of how much water is in the soil of a plant');
INSERT INTO public.units VALUES (14, 'system status', 'a measurement of the operational functioning of the observer');
INSERT INTO public.units VALUES (10, 'degrees F', 'a measurement of temperature in degrees Fahrienheit');
INSERT INTO public.units VALUES (19, 'seed packet', 'One seed packet.');
INSERT INTO public.units VALUES (6, 'ear', 'Example: corn.');
INSERT INTO public.units VALUES (15, 'date-time', 'a measurement of time, including both date and time (calendar and clock)');
INSERT INTO public.units VALUES (20, 'seeds', 'A count of seeds.');
INSERT INTO public.units VALUES (22, 'filename of image showing time, inside-temperature, and outside-temperature', 'LCD read-out, PNG format');
INSERT INTO public.units VALUES (16, 'time and labor', 'time and labor; barter goods; time it was done; cost in human effort;');
INSERT INTO public.units VALUES (18, 'oz', 'One ounce as weight.');
INSERT INTO public.units VALUES (1, 'lb', 'Weight.');
INSERT INTO public.units VALUES (21, 'unknown', 'Used when units is not known.');
INSERT INTO public.units VALUES (17, 're-closable bag', 'A small plastic baggie, the kind that has a re-closable top.');
